name: Flutter CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    uses: ./.github/workflows/flutter_format.yml

  test:
    uses: ./.github/workflows/flutter_test.yml

  build:
    needs: [format, test]
    uses: ./.github/workflows/flutter_build.yml